spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/btl
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: admin
      password: 1

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: tKxu2VHJgmOdg2F4GTQOBR0N21Vgo1DqH4bCDIVP2LU=
  expiration-ms: 86400000 # 1 ngày
  cookie-name: session_token

server:
  address: 0.0.0.0
  port: 8080
